ARG NODE_VERSION=18.18.2
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION
WORKDIR /app

RUN apt-get update && apt-get install -y \
	libcairo2-dev \
	libjpeg-dev \
	libpango1.0-dev \
	libgif-dev \
	libpng-dev \
	build-essential \
	g++

COPY . .

RUN yarn install --frozen-lockfile
RUN yarn lerna bootstrap

ENV NODE_ENV development

EXPOSE $SERVER_PORT

CMD ['yarn', '&&', 'yarn', 'dev']
