version: '3'

services:
  pixel-punch-app:
    container_name: pixel-punch-app
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    networks:
      - awesome-network
    command: node --experimental-specifier-resolution=node /app/server/dist/src/index.js

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    networks:
      - awesome-network

volumes:
  postgres:

networks:
  awesome-network:
    driver: bridge
