version: '3'

services:
  pixel-punch-app:
    container_name: pixel-punch-app
    build:
      context: .
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - postgres
    command: npm run dev:server

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres
volumes:
  postgres:
networks:
  postgres:
    driver: bridge
