version: '3'

services:
  app:
    platform: linux/amd64
    container_name: pixel-punch-app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - pgadmin
      - postgres
    ports:
      - '3001:3001'
    command: node --experimental-specifier-resolution=node /app/server/dist/src/index.js

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /tmp
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_PORT}'
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
