version: '3'

services:
  pixel-punch-app:
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    command: node --experimental-specifier-resolution=node /app/server/dist/src/index.js

  nginx:
    depends_on:
      - pixel-punch-app
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt/live/pixelpunch.ya-praktikum.tech/fullchain.pem:/etc/letsencrypt/live/pixelpunch.ya-praktikum.tech/fullchain.pem
      - /etc/letsencrypt/live/pixelpunch.ya-praktikum.tech/privkey.pem:/etc/letsencrypt/live/pixelpunch.ya-praktikum.tech/privkey.pem
    ports:
      - '80:80'
      - '443:443'

  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /tmp
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    restart: always
