FROM node:20

RUN apt-get update && apt-get install -y \
	libcairo2-dev \
	libjpeg-dev \
	libpango1.0-dev \
	libgif-dev \
	libpng-dev \
	build-essential \
	g++
WORKDIR /pixel-punch/app
COPY package.json ./
COPY packages ./packages
RUN npm install --force
EXPOSE 3001
